name: liveasy_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  firebase_auth:
  firebase_core:
  cloud_firestore:

  # flutter_localizations is included automatically with Flutter
  # You don't need to add it manually in the dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/hi.json
    - assets/lang/mr.json
    - assets/lang/otp/en.json
    - assets/lang/otp/hi.json
    - assets/lang/otp/mr.json
    - assets/lang/verification/en.json
    - assets/lang/verification/hi.json
    - assets/lang/verification/mr.json


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
