// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtA3VTHwfpzl2naUIEQ2mXowAUxnSVmFY',
    appId: '1:142098143376:web:44d1eedd4d67e580906015',
    messagingSenderId: '142098143376',
    projectId: 'liveasyapp-bb931',
    authDomain: 'liveasyapp-bb931.firebaseapp.com',
    storageBucket: 'liveasyapp-bb931.appspot.com',
    measurementId: 'G-0E6YNYXPJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAva1W4VJTUWMnXmmRLl420EgM2KDoW7wA',
    appId: '1:142098143376:android:eb7a9e55187156da906015',
    messagingSenderId: '142098143376',
    projectId: 'liveasyapp-bb931',
    storageBucket: 'liveasyapp-bb931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_5ToDArRd9TeIDUDRZjpPnMuIH6tlrc',
    appId: '1:142098143376:ios:dd21577f720e9ae2906015',
    messagingSenderId: '142098143376',
    projectId: 'liveasyapp-bb931',
    storageBucket: 'liveasyapp-bb931.appspot.com',
    iosBundleId: 'com.example.liveasyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq_5ToDArRd9TeIDUDRZjpPnMuIH6tlrc',
    appId: '1:142098143376:ios:dd21577f720e9ae2906015',
    messagingSenderId: '142098143376',
    projectId: 'liveasyapp-bb931',
    storageBucket: 'liveasyapp-bb931.appspot.com',
    iosBundleId: 'com.example.liveasyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtA3VTHwfpzl2naUIEQ2mXowAUxnSVmFY',
    appId: '1:142098143376:web:7a6da4a9df240340906015',
    messagingSenderId: '142098143376',
    projectId: 'liveasyapp-bb931',
    authDomain: 'liveasyapp-bb931.firebaseapp.com',
    storageBucket: 'liveasyapp-bb931.appspot.com',
    measurementId: 'G-E85Z67NYQJ',
  );
}
